# Generated by Django 5.2.4 on 2025-08-05 23:42

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restaurant', '0002_alter_booking_no_of_guests_alter_menu_inventory_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='No_of_guests',
            new_name='NoOfGusts',
        ),
        migrations.AddField(
            model_name='booking',
            name='PhoneNumber',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message='Phone number must be a 10-digit number, start with 05...', regex='^\\d{10}$')]),
        ),
    ]
